version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, ci]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, web]
    versioning-strategy: increase

  - package-ecosystem: npm
    directory: /studio
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, mobile]
    versioning-strategy: increase

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, python]
