// Generated by scripts/generate.py. Do not edit.
#pragma once
#include <Arduino.h>

namespace notefall::layout {
constexpr uint8_t kFirstMidiNote = 21;
constexpr uint8_t kLastMidiNote = 108;
constexpr size_t kNoteCount = 88;
constexpr size_t kPixelCount = 176;
constexpr uint8_t kDataPin = 11;
constexpr uint8_t kClockPin = 12;
constexpr uint32_t kSpiHz = 8000000UL;
constexpr uint8_t kMaxGlobalBrightness = 4;
constexpr uint8_t kDefaultGlobalBrightness = 2;
constexpr uint32_t kTargetStaleMs = 3000UL;
constexpr uint16_t kPixelByNote[kNoteCount] = {
    1, 3, 5, 8, 10, 11, 13, 15, 18, 20, 22, 23, 25, 27, 28, 32,
    33, 35, 37, 38, 42, 44, 45, 47, 49, 50, 52, 55, 57, 59, 60, 62,
    66, 67, 69, 71, 72, 74, 76, 79, 81, 82, 84, 86, 89, 91, 93, 94,
    96, 98, 99, 103, 104, 106, 108, 109, 113, 115, 116, 118, 120, 121, 123, 126,
    128, 130, 131, 133, 137, 138, 140, 142, 143, 145, 147, 150, 152, 153, 155, 157,
    160, 162, 164, 165, 167, 169, 170, 174
};
}  // namespace notefall::layout
