// Generated by mechanical/generate.py. Do not edit by hand.
#pragma once
#include <Arduino.h>

namespace notefall::layout {
constexpr uint8_t kRows = 4;
constexpr uint8_t kNotes = 12;
constexpr uint16_t kPixelsPerRow = 24;
constexpr uint16_t kPixelCount = 96;
constexpr uint8_t kFirstMidiNote = 60;
constexpr uint8_t kDataPin = 11;
constexpr uint8_t kClockPin = 12;
constexpr uint32_t kSpiHz = 4000000UL;
constexpr uint8_t kMaxGlobalBrightness = 4;
constexpr uint32_t kFailsafeMs = 1000UL;
constexpr uint16_t kPixelByRowNote[kRows][kNotes] = {
    {1, 3, 5, 6, 8, 12, 13, 15, 17, 18, 20, 22},
    {46, 44, 42, 41, 39, 35, 34, 32, 30, 29, 27, 25},
    {49, 51, 53, 54, 56, 60, 61, 63, 65, 66, 68, 70},
    {94, 92, 90, 89, 87, 83, 82, 80, 78, 77, 75, 73}
};
}  // namespace notefall::layout
