// Generated by scripts/generate.py. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace notefall::layout {
constexpr uint8_t kFirstMidiNote = 21;
constexpr uint8_t kLastMidiNote = 108;
constexpr std::size_t kNoteCount = 88;
constexpr std::size_t kPixelCount = 176;
constexpr uint8_t kDataPin = 11;
constexpr uint8_t kClockPin = 12;
constexpr uint32_t kSpiHz = 8000000UL;
constexpr uint8_t kMaxGlobalBrightness = 4;
constexpr uint8_t kDefaultGlobalBrightness = 2;
constexpr uint32_t kTargetStaleMs = 3000UL;
constexpr uint16_t kPixelByNote[kNoteCount] = {
    2, 3, 5, 9, 10, 12, 14, 15, 19, 20, 22, 24, 25, 27, 29, 32,
    33, 35, 37, 38, 42, 43, 45, 47, 49, 50, 52, 55, 57, 59, 60, 62,
    65, 67, 69, 71, 72, 74, 76, 79, 81, 82, 84, 86, 89, 91, 93, 94,
    96, 98, 99, 103, 104, 106, 107, 109, 112, 114, 116, 117, 119, 121, 122, 126,
    128, 129, 131, 133, 136, 138, 139, 141, 143, 144, 146, 150, 151, 153, 155, 156,
    160, 161, 163, 165, 166, 168, 170, 173
};
}  // namespace notefall::layout
