"""Generate manufacturing exports, layout metadata, and firmware mapping."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import cadquery as cq
from cadquery import exporters

from model import ROOT, build_assembly, build_parts, layout_from_config, load_config, logical_to_physical_map


EXPORT_DIR = ROOT / "mechanical" / "exports"
FIRMWARE_HEADER = ROOT / "firmware" / "include" / "layout_generated.h"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def bounds(shape: cq.Workplane) -> dict[str, float]:
    box = shape.val().BoundingBox()
    return {
        "x_mm": round(box.xlen, 4),
        "y_mm": round(box.ylen, 4),
        "z_mm": round(box.zlen, 4),
        "volume_mm3": round(shape.val().Volume(), 3),
    }


def render_firmware_header(layout_data: dict[str, Any], cfg: dict[str, Any]) -> str:
    rows = layout_data["physical_pixel_by_row_note"]
    mapping_lines = ",\n".join(
        "    {" + ", ".join(str(value) for value in row) + "}" for row in rows
    )
    led = cfg["led"]
    proto = cfg["protocol"]
    return f"""// Generated by mechanical/generate.py. Do not edit by hand.
#pragma once
#include <Arduino.h>

namespace notefall::layout {{
constexpr uint8_t kRows = {layout_data['row_count']};
constexpr uint8_t kNotes = {layout_data['note_count']};
constexpr uint16_t kPixelsPerRow = {layout_data['pixels_per_row']};
constexpr uint16_t kPixelCount = {layout_data['total_pixels']};
constexpr uint8_t kFirstMidiNote = {layout_data['first_midi_note']};
constexpr uint8_t kDataPin = {int(led['data_pin'])};
constexpr uint8_t kClockPin = {int(led['clock_pin'])};
constexpr uint32_t kSpiHz = {int(led['spi_hz'])}UL;
constexpr uint8_t kMaxGlobalBrightness = {int(led['max_global_brightness'])};
constexpr uint32_t kFailsafeMs = {int(proto['failsafe_ms'])}UL;
constexpr uint16_t kPixelByRowNote[kRows][kNotes] = {{
{mapping_lines}
}};
}}  // namespace notefall::layout
"""


def generate(check_only: bool = False) -> dict[str, Any]:
    cfg = load_config()
    layout = layout_from_config(cfg)
    layout_data = logical_to_physical_map(layout)

    # Layout checks happen before slow CAD exports.
    nearest = layout_data["nearest_pixel_in_row"]
    if len(set(nearest)) != layout.note_count:
        raise RuntimeError("Two notes map to one physical pixel in the V0 row")
    if layout_data["max_abs_mapping_error_mm"] > layout.led_pitch_mm / 2.0 + 1e-6:
        raise RuntimeError("Nearest-pixel error exceeds half an LED pitch")

    parts = build_parts(cfg)
    for name, part in parts.items():
        if not part.val().isValid():
            raise RuntimeError(f"{name} is not a valid solid")
        size = bounds(part)
        if size["x_mm"] > 220.0 or size["y_mm"] > 220.0:
            raise RuntimeError(f"{name} exceeds the 220 mm V0 print bed: {size}")

    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    FIRMWARE_HEADER.parent.mkdir(parents=True, exist_ok=True)

    file_entries: list[dict[str, Any]] = []
    for name, part in parts.items():
        for suffix in ("stl", "step"):
            path = EXPORT_DIR / f"v0_{name}.{suffix}"
            exporters.export(part, str(path), tolerance=0.02, angularTolerance=0.1)
            file_entries.append({"file": path.name, "sha256": sha256_file(path)})

    assembly_path = EXPORT_DIR / "v0_assembly.step"
    build_assembly(cfg, parts).save(str(assembly_path))
    file_entries.append({"file": assembly_path.name, "sha256": sha256_file(assembly_path)})

    layout_path = EXPORT_DIR / "layout.json"
    layout_path.write_text(json.dumps(layout_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    file_entries.append({"file": layout_path.name, "sha256": sha256_file(layout_path)})

    FIRMWARE_HEADER.write_text(render_firmware_header(layout_data, cfg), encoding="utf-8")

    manifest = {
        "schema_version": 1,
        "source_config": "config/system.json",
        "config_sha256": sha256_file(ROOT / "config" / "system.json"),
        "parts": {name: bounds(part) for name, part in parts.items()},
        "layout": {
            "total_pixels": layout_data["total_pixels"],
            "max_abs_mapping_error_mm": layout_data["max_abs_mapping_error_mm"],
            "unique_note_pixels_per_row": len(set(nearest)),
        },
        "files": file_entries,
    }
    manifest_path = EXPORT_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    if check_only:
        required = {entry["file"] for entry in file_entries}
        actual = {path.name for path in EXPORT_DIR.iterdir() if path.is_file()}
        missing = sorted(required - actual)
        if missing:
            raise RuntimeError(f"Missing generated exports: {missing}")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="also assert export presence and print-bed limits")
    args = parser.parse_args()
    manifest = generate(check_only=args.check)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
