"""Generate the 88-key LED map, firmware constants, CAD exports, and manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

import cadquery as cq
from cadquery import exporters


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from mechanical.model import build_full_rail_assembly, build_parts, rail_dimensions  # noqa: E402


CONFIG_PATH = ROOT / "config" / "system.json"
GENERATED_DIR = ROOT / "generated"
EXPORT_DIR = ROOT / "mechanical" / "exports"
FIRMWARE_HEADER = ROOT / "firmware" / "include" / "layout_generated.h"
FIXED_STEP_TIMESTAMP = "1970-01-01T00:00:00"

WHITE_PITCH_CLASSES = {0, 2, 4, 5, 7, 9, 11}


def load_config() -> dict[str, Any]:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def key_centers(config: dict[str, Any]) -> list[float]:
    piano = config["piano"]
    pitch = float(piano["white_key_pitch_mm"])
    first = int(piano["first_midi_note"])
    last = int(piano["last_midi_note"])
    centers: list[float] = []
    whites_seen = 0
    for note in range(first, last + 1):
        if note % 12 in WHITE_PITCH_CLASSES:
            centers.append((whites_seen + 0.5) * pitch)
            whites_seen += 1
        else:
            centers.append(whites_seen * pitch)
    if whites_seen != int(piano["white_key_count"]):
        raise ValueError(f"expected 52 white keys, found {whites_seen}")
    return centers


def build_layout(config: dict[str, Any]) -> dict[str, Any]:
    piano = config["piano"]
    led = config["led"]
    keybed_span = float(piano["keybed_span_mm"])
    pixel_count = int(led["pixel_count"])
    led_pitch = 1000.0 / float(led["pixels_per_m"])
    strip_span = pixel_count * led_pitch
    strip_left = (keybed_span - strip_span) / 2.0
    led_centers = [strip_left + (index + 0.5) * led_pitch for index in range(pixel_count)]
    keys = key_centers(config)
    mapping = [min(range(pixel_count), key=lambda i: abs(led_centers[i] - x)) for x in keys]
    errors = [led_centers[pixel] - key_x for pixel, key_x in zip(mapping, keys)]
    return {
        "schema_version": 2,
        "first_midi_note": int(piano["first_midi_note"]),
        "last_midi_note": int(piano["last_midi_note"]),
        "note_count": len(keys),
        "pixel_count": pixel_count,
        "led_pitch_mm": led_pitch,
        "strip_span_mm": strip_span,
        "keybed_span_mm": keybed_span,
        "key_centers_mm": keys,
        "led_centers_mm": led_centers,
        "pixel_by_note": mapping,
        "mapping_error_mm": errors,
        "max_abs_mapping_error_mm": max(abs(value) for value in errors),
    }


def render_header(config: dict[str, Any], layout: dict[str, Any]) -> str:
    led = config["led"]
    practice = config["practice"]
    mapping_lines = []
    values = layout["pixel_by_note"]
    for start in range(0, len(values), 16):
        mapping_lines.append("    " + ", ".join(str(value) for value in values[start : start + 16]))
    mapping_text = ",\n".join(mapping_lines)
    return f"""// Generated by scripts/generate.py. Do not edit.
#pragma once
#include <Arduino.h>

namespace notefall::layout {{
constexpr uint8_t kFirstMidiNote = {layout['first_midi_note']};
constexpr uint8_t kLastMidiNote = {layout['last_midi_note']};
constexpr size_t kNoteCount = {layout['note_count']};
constexpr size_t kPixelCount = {layout['pixel_count']};
constexpr uint8_t kDataPin = {int(led['data_pin'])};
constexpr uint8_t kClockPin = {int(led['clock_pin'])};
constexpr uint32_t kSpiHz = {int(led['spi_hz'])}UL;
constexpr uint8_t kMaxGlobalBrightness = {int(led['max_global_brightness'])};
constexpr uint8_t kDefaultGlobalBrightness = {int(led['default_global_brightness'])};
constexpr uint32_t kTargetStaleMs = {int(practice['target_stale_ms'])}UL;
constexpr uint16_t kPixelByNote[kNoteCount] = {{
{mapping_text}
}};
}}  // namespace notefall::layout
"""


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def normalize_step_header(path: Path) -> None:
    """Remove OpenCascade's wall-clock timestamp so exports are reproducible."""
    content = path.read_text(encoding="utf-8")
    normalized, replacements = re.subn(
        r"(FILE_NAME\([^,]+,)'[^']*'",
        rf"\1'{FIXED_STEP_TIMESTAMP}'",
        content,
        count=1,
    )
    if replacements != 1:
        raise RuntimeError(f"unable to normalize STEP timestamp: {path}")
    path.write_text(normalized, encoding="utf-8", newline="\n")


def bounds(part: cq.Workplane) -> dict[str, float]:
    box = part.val().BoundingBox()
    return {
        "x_mm": round(box.xlen, 3),
        "y_mm": round(box.ylen, 3),
        "z_mm": round(box.zlen, 3),
        "volume_mm3": round(part.val().Volume(), 1),
    }


def generate(check: bool = False) -> dict[str, Any]:
    config = load_config()
    layout = build_layout(config)
    led_pitch = float(layout["led_pitch_mm"])
    if layout["max_abs_mapping_error_mm"] > led_pitch / 2.0 + 1e-6:
        raise RuntimeError("note-to-pixel mapping exceeds half an LED pitch")
    if len(set(layout["pixel_by_note"])) != 88:
        raise RuntimeError("two piano keys map to the same primary pixel")

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    FIRMWARE_HEADER.parent.mkdir(parents=True, exist_ok=True)
    layout_path = GENERATED_DIR / "layout.json"
    layout_path.write_text(json.dumps(layout, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    FIRMWARE_HEADER.write_text(render_header(config, layout), encoding="utf-8")

    parts = build_parts(config)
    part_manifest: dict[str, Any] = {}
    files: list[dict[str, str]] = []
    for name, part in parts.items():
        if not part.val().isValid():
            raise RuntimeError(f"invalid solid: {name}")
        part_manifest[name] = bounds(part)
        for suffix in ("stl", "step"):
            path = EXPORT_DIR / f"{name}.{suffix}"
            exporters.export(part, str(path), tolerance=0.025, angularTolerance=0.12)
            if suffix == "step":
                normalize_step_header(path)
            files.append({"file": path.name, "sha256": sha256(path)})

    assembly_path = EXPORT_DIR / "full_88_rail_assembly.step"
    build_full_rail_assembly(config).save(str(assembly_path))
    normalize_step_header(assembly_path)

    dims = rail_dimensions(config)
    manifest = {
        "schema_version": 2,
        "config_sha256": sha256(CONFIG_PATH),
        "layout_sha256": sha256(layout_path),
        "layout": {
            "notes": layout["note_count"],
            "pixels": layout["pixel_count"],
            "max_abs_mapping_error_mm": layout["max_abs_mapping_error_mm"],
        },
        "rail": {
            "total_length_mm": dims.total_length,
            "segment_count": dims.segment_count,
            "nominal_segment_length_mm": dims.segment_length,
            "print_quantities": {
                "rail_left_end": 1,
                "rail_segment": dims.segment_count - 2,
                "rail_right_end": 1,
                "diffuser_segment": dims.segment_count,
            },
        },
        "parts": part_manifest,
        "files": files,
        "assembly": {
            "file": assembly_path.name,
            "purpose": "reference assembly; manufacture the hashed individual parts above",
        },
    }
    manifest_path = EXPORT_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    if check:
        for name, size in part_manifest.items():
            if size["x_mm"] > 220.0 or size["y_mm"] > 220.0:
                raise RuntimeError(f"{name} exceeds a 220x220 mm printer: {size}")
        if abs(dims.total_length - float(config["mechanical"]["rail_total_length_mm"])) > 1e-6:
            raise RuntimeError("rail segment sum does not match configured total")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    print(json.dumps(generate(check=args.check), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
