"""Generate the 88-key LED map, firmware constants, CAD exports, and manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

import cadquery as cq
from cadquery import exporters


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from mechanical.model import build_parts  # noqa: E402


CONFIG_PATH = ROOT / "config" / "system.json"
GENERATED_DIR = ROOT / "generated"
EXPORT_DIR = ROOT / "mechanical" / "exports"
FIRMWARE_HEADER = ROOT / "firmware" / "include" / "layout_generated.h"
FIXED_STEP_TIMESTAMP = "1970-01-01T00:00:00"

WHITE_PITCH_CLASSES = {0, 2, 4, 5, 7, 9, 11}


def load_config() -> dict[str, Any]:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def key_centers(config: dict[str, Any]) -> list[float]:
    piano = config["piano"]
    pitch = float(piano["white_key_pitch_mm"])
    first = int(piano["first_midi_note"])
    last = int(piano["last_midi_note"])
    centers: list[float] = []
    whites_seen = 0
    for note in range(first, last + 1):
        if note % 12 in WHITE_PITCH_CLASSES:
            centers.append((whites_seen + 0.5) * pitch)
            whites_seen += 1
        else:
            centers.append(whites_seen * pitch)
    if whites_seen != int(piano["white_key_count"]):
        raise ValueError(f"expected 52 white keys, found {whites_seen}")
    return centers


def build_layout(config: dict[str, Any]) -> dict[str, Any]:
    piano = config["piano"]
    led = config["led"]
    keybed_span = float(piano["keybed_span_mm"])
    pixel_count = int(led["pixel_count"])
    led_pitch = 1000.0 / float(led["pixels_per_m"])
    strip_span = pixel_count * led_pitch
    strip_left = (keybed_span - strip_span) / 2.0
    led_centers = [strip_left + (index + 0.5) * led_pitch for index in range(pixel_count)]
    keys = key_centers(config)
    mapping = [min(range(pixel_count), key=lambda i: abs(led_centers[i] - x)) for x in keys]
    errors = [led_centers[pixel] - key_x for pixel, key_x in zip(mapping, keys)]
    return {
        "schema_version": 2,
        "first_midi_note": int(piano["first_midi_note"]),
        "last_midi_note": int(piano["last_midi_note"]),
        "note_count": len(keys),
        "pixel_count": pixel_count,
        "led_pitch_mm": led_pitch,
        "strip_span_mm": strip_span,
        "keybed_span_mm": keybed_span,
        "key_centers_mm": keys,
        "led_centers_mm": led_centers,
        "pixel_by_note": mapping,
        "mapping_error_mm": errors,
        "max_abs_mapping_error_mm": max(abs(value) for value in errors),
    }


def build_power_budget(config: dict[str, Any]) -> dict[str, Any]:
    led = config["led"]
    power = config["power"]
    full_white_w = int(led["pixel_count"]) * float(power["conservative_full_white_w_per_pixel"])
    capped_led_w = full_white_w * int(led["max_global_brightness"]) / 31.0
    led_a = capped_led_w / float(power["supply_v"])
    design_a = led_a + float(power["controller_reserve_a"])
    branch_a = led_a / len(power["injection"])
    round_trip_resistance = (
        2 * float(power["max_injection_one_way_m"]) * float(power["wire_resistance_ohm_per_m"])
    )
    drop_v = branch_a * round_trip_resistance
    return {
        "schema_version": 1,
        "full_white_uncapped_w": round(full_white_w, 3),
        "firmware_capped_led_w": round(capped_led_w, 3),
        "firmware_capped_led_a": round(led_a, 3),
        "controller_reserve_a": float(power["controller_reserve_a"]),
        "design_current_a": round(design_a, 3),
        "supply_a": float(power["supply_a"]),
        "supply_utilization_percent": round(design_a / float(power["supply_a"]) * 100, 1),
        "fuse_a": float(power["fuse_a"]),
        "wire_awg": int(power["power_wire_awg"]),
        "wire_conservative_a": float(power["wire_conservative_a"]),
        "injection_count": len(power["injection"]),
        "worst_branch_current_a": round(branch_a, 3),
        "max_injection_one_way_m": float(power["max_injection_one_way_m"]),
        "worst_branch_drop_v": round(drop_v, 3),
        "worst_branch_drop_percent": round(drop_v / float(power["supply_v"]) * 100, 2),
    }


def render_header(config: dict[str, Any], layout: dict[str, Any]) -> str:
    led = config["led"]
    practice = config["practice"]
    mapping_lines = []
    values = layout["pixel_by_note"]
    for start in range(0, len(values), 16):
        mapping_lines.append("    " + ", ".join(str(value) for value in values[start : start + 16]))
    mapping_text = ",\n".join(mapping_lines)
    return f"""// Generated by scripts/generate.py. Do not edit.
#pragma once
#include <Arduino.h>

namespace notefall::layout {{
constexpr uint8_t kFirstMidiNote = {layout['first_midi_note']};
constexpr uint8_t kLastMidiNote = {layout['last_midi_note']};
constexpr size_t kNoteCount = {layout['note_count']};
constexpr size_t kPixelCount = {layout['pixel_count']};
constexpr uint8_t kDataPin = {int(led['data_pin'])};
constexpr uint8_t kClockPin = {int(led['clock_pin'])};
constexpr uint32_t kSpiHz = {int(led['spi_hz'])}UL;
constexpr uint8_t kMaxGlobalBrightness = {int(led['max_global_brightness'])};
constexpr uint8_t kDefaultGlobalBrightness = {int(led['default_global_brightness'])};
constexpr uint32_t kTargetStaleMs = {int(practice['target_stale_ms'])}UL;
constexpr uint16_t kPixelByNote[kNoteCount] = {{
{mapping_text}
}};
}}  // namespace notefall::layout
"""


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def normalize_step_header(path: Path) -> None:
    """Remove OpenCascade's wall-clock timestamp so exports are reproducible."""
    content = path.read_text(encoding="utf-8")
    normalized, replacements = re.subn(
        r"(FILE_NAME\([^,]+,)'[^']*'",
        rf"\1'{FIXED_STEP_TIMESTAMP}'",
        content,
        count=1,
    )
    if replacements != 1:
        raise RuntimeError(f"unable to normalize STEP timestamp: {path}")
    path.write_text(normalized, encoding="utf-8", newline="\n")


def bounds(part: cq.Workplane) -> dict[str, float]:
    box = part.val().BoundingBox()
    return {
        "x_mm": round(box.xlen, 3),
        "y_mm": round(box.ylen, 3),
        "z_mm": round(box.zlen, 3),
        "volume_mm3": round(part.val().Volume(), 1),
    }


def generate_into(
    generated_dir: Path,
    export_dir: Path,
    firmware_header: Path,
    check_constraints: bool,
) -> dict[str, Any]:
    config = load_config()
    layout = build_layout(config)
    led_pitch = float(layout["led_pitch_mm"])
    if layout["max_abs_mapping_error_mm"] > led_pitch / 2.0 + 1e-6:
        raise RuntimeError("note-to-pixel mapping exceeds half an LED pitch")
    if len(set(layout["pixel_by_note"])) != 88:
        raise RuntimeError("two piano keys map to the same primary pixel")

    generated_dir.mkdir(parents=True, exist_ok=True)
    export_dir.mkdir(parents=True, exist_ok=True)
    firmware_header.parent.mkdir(parents=True, exist_ok=True)
    layout_path = generated_dir / "layout.json"
    power_path = generated_dir / "power_budget.json"
    layout_path.write_text(json.dumps(layout, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    power_budget = build_power_budget(config)
    power_path.write_text(json.dumps(power_budget, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    firmware_header.write_text(render_header(config, layout), encoding="utf-8")

    parts = build_parts(config)
    part_manifest: dict[str, Any] = {}
    files: list[dict[str, str]] = []
    for name, part in parts.items():
        if not part.val().isValid():
            raise RuntimeError(f"invalid solid: {name}")
        part_manifest[name] = bounds(part)
        for suffix in ("stl", "step"):
            path = export_dir / f"{name}.{suffix}"
            exporters.export(part, str(path), tolerance=0.025, angularTolerance=0.12)
            if suffix == "step":
                normalize_step_header(path)
            files.append({"file": path.name, "sha256": sha256(path)})

    mech = config["mechanical"]
    manifest = {
        "schema_version": 3,
        "config_sha256": sha256(CONFIG_PATH),
        "layout_sha256": sha256(layout_path),
        "power_budget_sha256": sha256(power_path),
        "layout": {
            "notes": layout["note_count"],
            "pixels": layout["pixel_count"],
            "max_abs_mapping_error_mm": layout["max_abs_mapping_error_mm"],
        },
        "keyboard_mount": {
            "type": mech["strip_mount"],
            "strip_orientation_deg": float(mech["strip_orientation_deg"]),
            "printed_parts": 0,
            "diffuser": False,
            "optional_carrier": {
                "material": mech["optional_carrier_material"],
                "length_mm": float(mech["optional_carrier_length_mm"]),
                "height_mm": float(mech["optional_carrier_height_mm"]),
                "thickness_mm": float(mech["optional_carrier_thickness_mm"]),
            },
        },
        "print_quantities": {"controller_tray": 1, "controller_lid": 1},
        "parts": part_manifest,
        "files": files,
    }
    manifest_path = export_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    if check_constraints:
        for name, size in part_manifest.items():
            if size["x_mm"] > 220.0 or size["y_mm"] > 220.0:
                raise RuntimeError(f"{name} exceeds a 220x220 mm printer: {size}")
        if abs(float(mech["strip_orientation_deg"]) - 90.0) > 1e-6:
            raise RuntimeError("the exposed strip must face the player at 90 degrees")
        if float(mech["optional_carrier_height_mm"]) < float(config["led"]["pcb_width_mm"]):
            raise RuntimeError("optional carrier is shorter than the vertical LED PCB")
        if power_budget["design_current_a"] >= power_budget["fuse_a"] * 0.8:
            raise RuntimeError("design current leaves insufficient fuse nuisance-trip margin")
        if power_budget["fuse_a"] > power_budget["wire_conservative_a"]:
            raise RuntimeError("fuse rating exceeds conservative wire rating")
        if power_budget["worst_branch_drop_percent"] > float(config["power"]["max_voltage_drop_percent"]):
            raise RuntimeError("power injection voltage drop exceeds configured limit")
    return manifest


def generate(check: bool = False) -> dict[str, Any]:
    if not check:
        return generate_into(GENERATED_DIR, EXPORT_DIR, FIRMWARE_HEADER, True)

    # A check must not rewrite committed manufacturing files. Generate an
    # independent candidate tree and compare bytes so CI can detect stale
    # artifacts without racing virus scanners, editors, or parallel jobs.
    with tempfile.TemporaryDirectory(prefix="notefall-generate-") as temporary:
        candidate_root = Path(temporary)
        candidate_generated = candidate_root / "generated"
        candidate_exports = candidate_root / "mechanical" / "exports"
        candidate_header = candidate_root / "firmware" / "include" / FIRMWARE_HEADER.name
        manifest = generate_into(
            candidate_generated, candidate_exports, candidate_header, True
        )
        pairs = [
            (candidate_generated / "layout.json", GENERATED_DIR / "layout.json"),
            (candidate_generated / "power_budget.json", GENERATED_DIR / "power_budget.json"),
            (candidate_header, FIRMWARE_HEADER),
        ]
        for candidate, committed in pairs:
            if not committed.is_file() or candidate.read_bytes() != committed.read_bytes():
                relative = committed.relative_to(ROOT)
                raise RuntimeError(
                    f"generated artifact is stale: {relative}; run python scripts/generate.py"
                )

        committed_manifest_path = EXPORT_DIR / "manifest.json"
        if not committed_manifest_path.is_file():
            raise RuntimeError("generated artifact is stale: mechanical/exports/manifest.json")
        committed_manifest = json.loads(committed_manifest_path.read_text(encoding="utf-8"))

        # OpenCascade serializes equivalent STL/STEP solids differently across
        # Windows and Linux. Compare platform-neutral geometry/config metadata,
        # then separately prove that every committed manufacturing file matches
        # its committed hash. This detects stale or tampered artifacts without
        # pretending cross-platform CAD bytes are identical.
        def semantic(value: dict[str, Any]) -> dict[str, Any]:
            result = dict(value)
            result["files"] = [entry["file"] for entry in value["files"]]
            return result

        if semantic(manifest) != semantic(committed_manifest):
            raise RuntimeError(
                "generated CAD metadata is stale; run python scripts/generate.py"
            )
        for entry in committed_manifest["files"]:
            path = EXPORT_DIR / entry["file"]
            if not path.is_file() or sha256(path) != entry["sha256"]:
                raise RuntimeError(f"manufacturing artifact hash mismatch: {path.relative_to(ROOT)}")
        return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    print(json.dumps(generate(check=args.check), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
